# Generated by Django 5.0.7 on 2024-07-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
