# Generated by Django 5.0.6 on 2024-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_section_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.TextField(choices=[('CC', 'C/C++'), ('PT', 'Python')], default='PT', max_length=2),
        ),
    ]
