# Generated by Django 5.2.1 on 2025-05-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_question_visible_section_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.TextField(choices=[('CC', 'C/C++'), ('PT', 'Python'), ('JP', 'Jupyter')], default='PT', max_length=2),
        ),
    ]
