# Generated by Django 5.0.6 on 2025-10-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_question_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.TextField(choices=[('CC', 'C/C++'), ('PT', 'Python'), ('JP', 'Jupyter'), ('JV', 'Java')], default='PT', max_length=2),
        ),
    ]
