# Generated by Django 5.0.6 on 2026-08-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_question_order_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.TextField(choices=[('CC', 'C/C++'), ('PT', 'Python'), ('JP', 'Jupyter'), ('JV', 'Java'), ('RL', 'Relax')], default='PT', max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.TextField(choices=[('WE', 'Waiting Evaluation'), ('FL', 'Fail'), ('SC', 'Success'), ('RN', 'Running'), ('IE', 'Internal Error')], default='WE', max_length=2),
        ),
        migrations.CreateModel(
            name='RelaxTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=100)),
                ('correct_query', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.question')),
            ],
        ),
    ]
