# Generated by Django 5.0.6 on 2026-09-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_question_language_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelaxTestInfo',
            new_name='DbTestInfo',
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.TextField(choices=[('CC', 'C/C++'), ('PT', 'Python'), ('JP', 'Jupyter'), ('JV', 'Java'), ('RL', 'Relax'), ('SQ', 'SQL')], default='PT', max_length=2),
        ),
    ]
