# Generated by Django 5.0.6 on 2026-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_question_language_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(default='Ccomp / Engcomp', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='2026/2', max_length=32),
        ),
    ]
