services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - backend/.env
    volumes:
      - ./backend:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend

  judge:
    build:
      context: ./backend
      dockerfile: Dockerfile.judge
    env_file: 
      - backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - backend


  
