
services:
  backend:
    image: backend:latest
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    command: bash -c "python manage.py setup && python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: frontend:latest
    env_file:
      - frontend/.env
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    command: ng serve --configuration=production --host 0.0.0.0 --port 8080

  judge:
    image: backend
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    command: python manage.py judge --verbose



