services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - backend/.env
    volumes:
      - ./backend:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - API_URL=http://api.seudominio.com
    volumes:
      - ./frontend:/app
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend

  
