FROM python:3.11-slim

# Set environment variables
WORKDIR /app

COPY requirements.txt ./

# Install dependencies
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py setup

# Expose the port
EXPOSE 8000
